Use redis 6.2.4 in CI
aio-libs/aioredis-py pull request #1045
Opened 2021-07-03 00:46 UTC by abrookins

## What do these changes do?

Use Redis 6.2.4. in CI.

## Are there changes in behavior for the user?

No.

## Related issue number

Relates to #930.

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

2021-07-03 15:37 UTC, Andrew-Chen-Wang requested changes
@abrookins I adjusted our tests for 6.2.4. We have a problem with pypy3 + uvloop though; not sure if it's our problem or uvloop or pypy. Also tested it twice on the CI and both times it failed.

Edit: potential reasoning? https://github.com/MagicStack/uvloop/issues/303#issuecomment-556007037

2021-07-03 17:20 UTC, abrookins commented
Awesome dude! I'll take a look.

2021-07-13 00:28 UTC, Andrew-Chen-Wang commented
awesome thanks @abrookins !

2021-07-13 00:29 UTC, Andrew-Chen-Wang approved these changes

2021-07-13 01:01 UTC, merged