Bump the version for 2.0.0 release
aio-libs/aioredis-py pull request #1075
Opened 2021-07-29 18:45 UTC by abrookins

## What do these changes do?

Bumps the version to 2.0.0 in prep for tagging the release.

## Are there changes in behavior for the user?

Yes, you could say that.

## Related issue number

#930 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

2021-07-29 20:22 UTC, Andrew-Chen-Wang requested changes
I'd like to address #1040 first

2021-07-29 20:23 UTC, Andrew-Chen-Wang commented
@abrookins L25 in setup.py needs to be changed

2021-07-29 20:56 UTC, seandstewart approved these changes

2021-07-29 21:07 UTC, Andrew-Chen-Wang approved these changes
Not sure if a fix for #1050 will be breaking in anyone's production, but we'll see. LGTM!!!

2021-07-30 02:04 UTC, abrookins commented
> Hi, may I ask Why don't you plan to support python3.6 ？

We'll add that back. I removed it while trying to fix #1040, but the attempt was unsuccessful. Also, we should be able to maintain compatibility either way.

2021-07-30 06:37 UTC, merged