Fix typing on blpop (etc) timeout argument
aio-libs/aioredis-py pull request #1224
Opened 2021-11-30 00:15 UTC by icgood

## What do these changes do?

Improves typing on [blpop](https://redis.io/commands/blpop)'s *timeout* argument, which is a number of seconds (not milliseconds) and allows decimal precision:

> The timeout argument is interpreted as a double value specifying the maximum number of seconds to block. A timeout of zero can be used to block indefinitely.

Other blocking `b*` methods were updated similarly. I also fixed some low-hanging mypy errors under `tests/`.

## Are there changes in behavior for the user?

No change in behavior, only type hint changes.

## Related issue number

N/A

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

2021-11-30 01:27 UTC, Andrew-Chen-Wang requested changes
Thanks! We'll want to change the name of the TimeoutSecT to something more specific to BL/BR ops because there are other arguments that also include a timeout argument.

2021-11-30 02:34 UTC, icgood commented
> We'll want to change the name of the TimeoutSecT to something more specific to BL/BR ops because there are other arguments that also include a timeout argument.

@Andrew-Chen-Wang Yeah, that was the reason I went with `TimeoutSecT`, to differentiate it from other `timeout=` arguments that take milliseconds. I verified that the spots I switched to `TimeoutSecT` were all documented as taking seconds, the same way as `BLPOP`. Would any of the following be preferable to you?

* `TimeoutSecondsT`
* `SecondsT`
* `TimeoutSecondsT` + `TimeoutMillisT` for millisecond values (simple alias for `int`).

2021-11-30 02:50 UTC, Andrew-Chen-Wang commented
I see. I fear that some other redis command would also have seconds for timeout arg. I was thinking in terms of blocking list like `BLTimeoutT`, but if the only redis commands that use `seconds`are the blocking list primitives, then I think the current state is fine.

2021-12-02 15:51 UTC, Andrew-Chen-Wang approved these changes
Thanks a lot!

2021-12-15 18:05 UTC, merged